/**
 * FILE: src/lib/init/navigation/preset.ts
 * PURPOSE: Navigation preset configuration
 * OWNERSHIP: CLI
 */

import { join } from 'path';
import { ensureDir, writeTextFile } from '../../fs';
import type { InitInputs } from '../types';

/**
 * Section 26, 29: Configures navigation preset file (System Zone).
 * Available for both Expo and Bare targets when React Navigation is selected.
 */
export function configureNavigationPreset(appRoot: string, inputs: InitInputs): void {
  if (!inputs.navigationPreset) {
    return;
  }

  // Ensure navigation directory exists (for both Expo and Bare)
  const navigationDir = join(appRoot, 'packages', '@rns', 'navigation');
  ensureDir(navigationDir);

  const presetFile = join(navigationDir, 'preset.ts');
  const content = `/**
 * FILE: packages/@rns/navigation/preset.ts
 * PURPOSE: Navigation preset selector (section 26, 29).
 * OWNERSHIP: CORE
 *
 * This file is generated by the CLI during init.
 * Available for both Expo and Bare targets when React Navigation is selected.
 */

export type NavigationPreset =
  | 'stack-only'
  | 'tabs-only'
  | 'stack-tabs'
  | 'stack-tabs-modals'
  | 'drawer';

export const NAVIGATION_PRESET: NavigationPreset = '${inputs.navigationPreset}';
`;

  writeTextFile(presetFile, content);
}
