/**
 * FILE: packages/@rns/navigation/preset.ts
 * PURPOSE: Navigation preset selector (section 26, 29).
 * OWNERSHIP: CORE
 *
 * This file is generated by the CLI during init.
 * Available for both Expo and Bare targets when React Navigation is selected.
 */

export type NavigationPreset =
  | 'stack-only'
  | 'tabs-only'
  | 'stack-tabs'
  | 'stack-tabs-modals'
  | 'drawer';

export const NAVIGATION_PRESET: NavigationPreset = 'stack-tabs-modals';
